name: Python CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install pipenv and dependencies
      run: |
        pip install pipenv
        pipenv install --dev --ignore-pipfile

    - name: Lint code
      run: |
        pipenv run pylint graniteclient

    - name: Run tests
      run: |
        pipenv run pytest --cov=graniteclient --cov-report=html tests/

    - name: Upload coverage report to SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_ACCESS_TO_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_UPLOAD_DATA_TOKEN }}

    - name: Pull Request Analysis Decorator
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_ACCESS_TO_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_UPLOAD_DATA_TOKEN }}
