name: Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read
  checks: write

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --dev --ignore-pipfile
          
      - name: Run tests and coverage
        run: pytest --cov=graniteclient --cov-report=xml

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.SONAR_ACCESS_TO_GITHUB }}
          SONAR_TOKEN: ${{ secrets.SONAR_UPLOAD_DATA_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=johan-ronnkvist_granite-client
            -Dsonar.organization=johan-ronnkvist
            -Dsonar.sources=graniteclient
            -Dsonar.tests=tests
            -Dsonar.test.inclusions=**/*_test.py,**/*_spec.py
            -Dsonar.python.coverage.reportPaths=coverage.xml

      - name: SonarQube Quality Gate Report
        uses: phwt/sonarqube-quality-gate-action@v1.3.2
