name: Build and Test
on: [pull_request]

permissions:
  contents: read

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        python-version: ['3.10']

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --dev

    - name: Test with pytest
      run: pipenv run pytest --cov=graniteclient --cov-report=xml

    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.SONAR_ACCESS_TO_GITHUB }}
        SONAR_TOKEN: ${{ secrets.SONAR_UPLOAD_DATA_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=johan-ronnkvist_granite-client
          -Dsonar.organization=johan-ronnkvist
          -Dsonar.sources=graniteclient
          -Dsonar.tests=tests
          -Dsonar.test.inclusions=**/*_test.py,**/*_spec.py
          -Dsonar.python.coverage.reportPaths=coverage.xml